version: "3.7"

services:
  database:
    image: mysql
    container_name: database_dcc060
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: admin
      MYSQL_PASSWORD: docker
    volumes:
      - mysql:/var/lib/mysql
  
  server:
    build: .
    container_name: app_dcc060
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    command: npm run dev
    environment:
      - DATABASE_URL=database_dcc060

volumes:
  mysql:
    driver: local